{"name": "test2", "status": "passed", "description": "\n        Test for two consecutive 0 in data.\n        ", "attachments": [{"name": "log", "source": "795e201c-9411-4de2-8c1a-9f4a76f6d371-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "b079cdd3-6552-49aa-ba52-57163804fb9c-attachment.txt", "type": "text/plain"}], "start": 1656452747583, "stop": 1656452747924, "uuid": "5bbedb04-6138-48a8-b314-8d3d2850e3fa", "historyId": "ef905c262589be9a77b4757f3e86766a", "testCaseId": "852c3e42abc3f4d45db96d50f9b9be11", "fullName": "research_amp.cc.test.test_detect_outliers.TestDetectOutliers#test2", "labels": [{"name": "parentSuite", "value": "research_amp.cc.test"}, {"name": "suite", "value": "test_detect_outliers"}, {"name": "subSuite", "value": "TestDetectOutliers"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "research_amp.cc.test.test_detect_outliers"}]}