[32mINFO    [0m helpers.hunit_test:hunit_test.py:912 17:30:43 - [36mINFO [0m hunit_test.py setUp:912            17:30:43 - [36mINFO [0m hunit_test.py setUp:912            
################################################################################
TestIgHistoricalPqByDateTaqBarClient1.test_read_data1
################################################################################
[32mINFO    [0m im_v2.ig.data.client.historical_bars:htqdm.py:42 17:30:43 - [36mINFO [0m htqdm.py flush:42                  17:30:43 - [36mINFO [0m htqdm.py flush:42                  Reading historical data from S3:   0%|          | 0/1 [00:00<?, ?it/s]
[32mINFO    [0m im_v2.ig.data.client.historical_bars:htqdm.py:42 17:30:45 - [36mINFO [0m htqdm.py flush:42                  17:30:45 - [36mINFO [0m htqdm.py flush:42                  Reading historical data from S3: 100%|##########| 1/1 [00:01<00:00,  1.90s/it]
[32mINFO    [0m im_v2.ig.data.client.historical_bars:htqdm.py:42 17:30:45 - [36mINFO [0m htqdm.py flush:42                  17:30:45 - [36mINFO [0m htqdm.py flush:42                  Reading historical data from S3: 100%|##########| 1/1 [00:01<00:00,  1.90s/it]
[32mINFO    [0m helpers.htimer:htimer.py:133 17:30:45 - [36mINFO [0m htimer.py dtimer_start:133                             17:30:45 - [36mINFO [0m htimer.py dtimer_start:133                             Process pd data ...
[32mINFO    [0m helpers.htimer:htimer.py:150 17:30:45 - [36mINFO [0m htimer.py dtimer_stop:150                              17:30:45 - [36mINFO [0m htimer.py dtimer_stop:150                              Process pd data done (0.010 s)
[33mWARNING [0m helpers.hdbg:hdbg.py:131 17:30:45 - [33mWARN [0m hdbg.py _dfatal:131                17:30:45 - [33mWARN [0m hdbg.py _dfatal:131                * Failed assertion *
val1 - val2=['17085']
val2 - val1=['17085.0']
val1=['17085']
set eq
val2=['17085.0']
Not all the requested symbols were retrieved
Continuing as per user request with only_warning=True