{"name": "test_redefined_function", "status": "passed", "description": "\n        If the cached function is redefined, but it's still the same, then the\n        intrinsic function should not be recomputed.\n        ", "attachments": [{"name": "log", "source": "aaa47221-a723-4181-8a17-e5248abc3d46-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "a07f7661-ab48-43d4-b900-efe0525945a4-attachment.txt", "type": "text/plain"}], "start": 1656452645848, "stop": 1656452645954, "uuid": "75e3849e-6d96-477a-9f69-80e018933dec", "historyId": "e783d960badca8af9f9f371b79b45737", "testCaseId": "ef89a3297bfea31f622c8d6d1b33b2db", "fullName": "helpers.test.test_cache.TestGlobalCache1#test_redefined_function", "labels": [{"name": "parentSuite", "value": "helpers.test"}, {"name": "suite", "value": "test_cache"}, {"name": "subSuite", "value": "TestGlobalCache1"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "helpers.test.test_cache"}]}