17:37:36 - [36mINFO [0m hunit_test.py setUp:912            
################################################################################
TestGetUniverseGeneral1.test_get_universe_invalid_vendor
################################################################################
