{"name": "test4", "status": "passed", "description": "\n        Test for a file `./core/dataflow/utils.py` that is from Docker (i.e.,\n        it starts with `/app`), but has multiple copies in the repo.\n        ", "attachments": [{"name": "log", "source": "7f627a2e-8d6d-4df8-b174-6dc8bb69f3b3-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "c01874b1-aa3a-44fd-b519-a65570709738-attachment.txt", "type": "text/plain"}], "start": 1656452257693, "stop": 1656452257695, "uuid": "1dcd3e01-4edb-4573-93b4-4e647cf58349", "historyId": "67788a50145dba16b63dedeec201431e", "testCaseId": "3628e50092168824b9a8c8b91e5bb89a", "fullName": "helpers.test.test_git.Test_find_docker_file1#test4", "labels": [{"name": "parentSuite", "value": "helpers.test"}, {"name": "suite", "value": "test_git"}, {"name": "subSuite", "value": "Test_find_docker_file1"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "helpers.test.test_git"}]}