{"name": "test_unknown_os1", "status": "passed", "description": "\n        Test unknown OS raises an error.\n        ", "attachments": [{"name": "log", "source": "95e80103-165a-4851-89af-9bcf89e32046-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "63180d71-1286-4c05-b1dc-554d8b4677ac-attachment.txt", "type": "text/plain"}], "start": 1656452652058, "stop": 1656452652060, "uuid": "40592b26-8156-465b-bc5e-64bf255b66ea", "historyId": "f52fbff2e9e427fb45393591014c4cbb", "testCaseId": "4a0c2d2124d0969a7b8aa669393a3206", "fullName": "helpers.test.test_open.Test_open_unknown#test_unknown_os1", "labels": [{"name": "parentSuite", "value": "helpers.test"}, {"name": "suite", "value": "test_open"}, {"name": "subSuite", "value": "Test_open_unknown"}, {"name": "host", "value": "8331b618a6a7"}, {"name": "thread", "value": "10537-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "helpers.test.test_open"}]}